//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCS.DNA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCS.DNA.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Navigation Azure.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad storage connection string.
        /// </summary>
        public static string BindCustBadConnect {
            get {
                return ResourceManager.GetString("BindCustBadConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad cloud customer name.
        /// </summary>
        public static string BindCustBadName {
            get {
                return ResourceManager.GetString("BindCustBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing customer name.
        /// </summary>
        public static string BindCustNoName {
            get {
                return ResourceManager.GetString("BindCustNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing job name.
        /// </summary>
        public static string BindJobNoName {
            get {
                return ResourceManager.GetString("BindJobNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad realm name.
        /// </summary>
        public static string BindRealmBadName {
            get {
                return ResourceManager.GetString("BindRealmBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad user name.
        /// </summary>
        public static string BindUserBadName {
            get {
                return ResourceManager.GetString("BindUserBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad cloud job name.
        /// </summary>
        public static string BinJobBadName {
            get {
                return ResourceManager.GetString("BinJobBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Job and User.
        /// </summary>
        public static string BusyConnectJobUser {
            get {
                return ResourceManager.GetString("BusyConnectJobUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect User and Customer.
        /// </summary>
        public static string BusyConnectUserCust {
            get {
                return ResourceManager.GetString("BusyConnectUserCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect User and Job.
        /// </summary>
        public static string BusyConnectUserJob {
            get {
                return ResourceManager.GetString("BusyConnectUserJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Database Report.
        /// </summary>
        public static string BusyDatabaseReport {
            get {
                return ResourceManager.GetString("BusyDatabaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Job and User.
        /// </summary>
        public static string BusyDisconnectJobUser {
            get {
                return ResourceManager.GetString("BusyDisconnectJobUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect User and Customer.
        /// </summary>
        public static string BusyDisconnectUserCust {
            get {
                return ResourceManager.GetString("BusyDisconnectUserCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect User and Job.
        /// </summary>
        public static string BusyDisconnectUserJob {
            get {
                return ResourceManager.GetString("BusyDisconnectUserJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Download.
        /// </summary>
        public static string BusyJobDownload {
            get {
                return ResourceManager.GetString("BusyJobDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Upload.
        /// </summary>
        public static string BusyJobUpload {
            get {
                return ResourceManager.GetString("BusyJobUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load job list.
        /// </summary>
        public static string BusyLoadJobList {
            get {
                return ResourceManager.GetString("BusyLoadJobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading navigation tree.
        /// </summary>
        public static string BusyLoadNavTree {
            get {
                return ResourceManager.GetString("BusyLoadNavTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load realm list.
        /// </summary>
        public static string BusyLoadRealmList {
            get {
                return ResourceManager.GetString("BusyLoadRealmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load user list.
        /// </summary>
        public static string BusyUserList {
            get {
                return ResourceManager.GetString("BusyUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating job {0}.
        /// </summary>
        public static string BusyValidateJob {
            get {
                return ResourceManager.GetString("BusyValidateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelLabel {
            get {
                return ResourceManager.GetString("ButtonCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonCloseLabel {
            get {
                return ResourceManager.GetString("ButtonCloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOKLabel {
            get {
                return ResourceManager.GetString("ButtonOKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If user {0} has forgotten their password, a temporary password can be assigned here. The user can use the temporary password to login and change the password to a secret value of their choice..
        /// </summary>
        public static string ChangePasswordInstructions {
            get {
                return ResourceManager.GetString("ChangePasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job&apos;s Container does not exist or is inaccessible..
        /// </summary>
        public static string CloudJobNoContainer {
            get {
                return ResourceManager.GetString("CloudJobNoContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (orphan container).
        /// </summary>
        public static string CloudNodeOrphanContainer {
            get {
                return ResourceManager.GetString("CloudNodeOrphanContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (orphan job).
        /// </summary>
        public static string CloudNodeOrphanJob {
            get {
                return ResourceManager.GetString("CloudNodeOrphanJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing licensing and cloud storage.
        /// </summary>
        public static string ComparingBusy {
            get {
                return ResourceManager.GetString("ComparingBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient connection values..
        /// </summary>
        public static string ConnectLackValues {
            get {
                return ResourceManager.GetString("ConnectLackValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading navigation tree... Please wait..
        /// </summary>
        public static string ConnectNavLoading {
            get {
                return ResourceManager.GetString("ConnectNavLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect successful. Closing Window... Please wait..
        /// </summary>
        public static string ConnectSuccess {
            get {
                return ResourceManager.GetString("ConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connect.
        /// </summary>
        public static string ConnectWaiting {
            get {
                return ResourceManager.GetString("ConnectWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container and licensing job record both exist..
        /// </summary>
        public static string ContainerAndJobOK {
            get {
                return ResourceManager.GetString("ContainerAndJobOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The container is an orphan. There is no licensing job record associated with the container..
        /// </summary>
        public static string ContainerOrphan {
            get {
                return ResourceManager.GetString("ContainerOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the currently selected customer..
        /// </summary>
        public static string CustEditDeleteTip {
            get {
                return ResourceManager.GetString("CustEditDeleteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display an input prompt to create a new customer..
        /// </summary>
        public static string CustEditNewTip {
            get {
                return ResourceManager.GetString("CustEditNewTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate the currently selected customer has an accessible Azure Storage Account.
        /// </summary>
        public static string CustEditValidateTip {
            get {
                return ResourceManager.GetString("CustEditValidateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect customer {0} to child user {1}.
        /// </summary>
        public static string CustomerConnectUser1 {
            get {
                return ResourceManager.GetString("CustomerConnectUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect customer {0} to {1} child users.
        /// </summary>
        public static string CustomerConnectUserN {
            get {
                return ResourceManager.GetString("CustomerConnectUserN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect customer {0} from child user {1}.
        /// </summary>
        public static string CustomerDisconnectUser {
            get {
                return ResourceManager.GetString("CustomerDisconnectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting customer {0}.
        /// </summary>
        public static string DeleteCustomerBusy {
            get {
                return ResourceManager.GetString("DeleteCustomerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete customer Id {0} Name &apos;{1}&apos;.
        ///
        ///Note: Deleting a customer removes it and its jobs from the licensing database, but it does NOT delete any existing Azure Storage Account or Containers that correspond to the customer and jobs..
        /// </summary>
        public static string DeleteCustomerPrompt {
            get {
                return ResourceManager.GetString("DeleteCustomerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect DNA Account Id or Password credentials..
        /// </summary>
        public static string DNABadCredentials {
            get {
                return ResourceManager.GetString("DNABadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorised to use this application..
        /// </summary>
        public static string DNANoAuth {
            get {
                return ResourceManager.GetString("DNANoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User email address is redundant because it is the same as the User name..
        /// </summary>
        public static string EmailRedundant {
            get {
                return ResourceManager.GetString("EmailRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container &apos;{0}&apos; is inaccessible. Do you want to continue and convert the container to a job?.
        /// </summary>
        public static string InaccessibleJobContainerPrompt {
            get {
                return ResourceManager.GetString("InaccessibleJobContainerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job is an orphan. There is no container associated with the licensing job record..
        /// </summary>
        public static string JobOrphan {
            get {
                return ResourceManager.GetString("JobOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string LabelAppCreated {
            get {
                return ResourceManager.GetString("LabelAppCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string LabelAppCredits {
            get {
                return ResourceManager.GetString("LabelAppCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LabelAppCustomer {
            get {
                return ResourceManager.GetString("LabelAppCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Location.
        /// </summary>
        public static string LabelAppDataLocation {
            get {
                return ResourceManager.GetString("LabelAppDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string LabelAppDisplayName {
            get {
                return ResourceManager.GetString("LabelAppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string LabelAppId {
            get {
                return ResourceManager.GetString("LabelAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string LabelAppInactive {
            get {
                return ResourceManager.GetString("LabelAppInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string LabelAppJobName {
            get {
                return ResourceManager.GetString("LabelAppJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelAppName {
            get {
                return ResourceManager.GetString("LabelAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Properties.
        /// </summary>
        public static string LabelAppOtherProperties {
            get {
                return ResourceManager.GetString("LabelAppOtherProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelAppPassword {
            get {
                return ResourceManager.GetString("LabelAppPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string LabelAppSequence {
            get {
                return ResourceManager.GetString("LabelAppSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Connect.
        /// </summary>
        public static string LabelAppStorageConnect {
            get {
                return ResourceManager.GetString("LabelAppStorageConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing container blobs.
        /// </summary>
        public static string ListJobsBusy {
            get {
                return ResourceManager.GetString("ListJobsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load customer list.
        /// </summary>
        public static string LoadCustomerListBusy {
            get {
                return ResourceManager.GetString("LoadCustomerListBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Licensing Provider….
        /// </summary>
        public static string LoadingProviderBusy {
            get {
                return ResourceManager.GetString("LoadingProviderBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait. Some providers may take a while to load or respond after a timeout due to an error..
        /// </summary>
        public static string LoadingProviderWait {
            get {
                return ResourceManager.GetString("LoadingProviderWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string MetricsApplicationCategory {
            get {
                return ResourceManager.GetString("MetricsApplicationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically connect on application start if previous successful credentials have been remembered. Press the Shift key on program start to prevent auto connect..
        /// </summary>
        public static string MetricsAutoConnectDesc {
            get {
                return ResourceManager.GetString("MetricsAutoConnectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Connect.
        /// </summary>
        public static string MetricsAutoConnectDisplay {
            get {
                return ResourceManager.GetString("MetricsAutoConnectDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Provider.
        /// </summary>
        public static string MetricsAutoProviderDisplay {
            get {
                return ResourceManager.GetString("MetricsAutoProviderDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Visibility.
        /// </summary>
        public static string MetricsCustVisibilityCategory {
            get {
                return ResourceManager.GetString("MetricsCustVisibilityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Uri of the base address of the Red Centre Software licensing web service. Only used for DNA Licence authentication..
        /// </summary>
        public static string MetricsLicensingUriDesc {
            get {
                return ResourceManager.GetString("MetricsLicensingUriDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing Uri.
        /// </summary>
        public static string MetricsLicensingUriDisplay {
            get {
                return ResourceManager.GetString("MetricsLicensingUriDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of Azure blobs that will be listed. Valid range is 500 to 20000..
        /// </summary>
        public static string MetricsMaxListBlobsDesc {
            get {
                return ResourceManager.GetString("MetricsMaxListBlobsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max List Blobs.
        /// </summary>
        public static string MetricsMaxListBlobsDisplay {
            get {
                return ResourceManager.GetString("MetricsMaxListBlobsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of items that will appear in log lists. Older excess items are dropped. Valid range is 50 to 2000..
        /// </summary>
        public static string MetricsMaxLogItemsDesc {
            get {
                return ResourceManager.GetString("MetricsMaxLogItemsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Log Items.
        /// </summary>
        public static string MetricsMaxLogItemsDisplay {
            get {
                return ResourceManager.GetString("MetricsMaxLogItemsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds to delay before saving a modified customer, job or user. Valid range is 0.5 to 5.0..
        /// </summary>
        public static string MetricsSaveDelaySecondsDesc {
            get {
                return ResourceManager.GetString("MetricsSaveDelaySecondsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Delay Seconds.
        /// </summary>
        public static string MetricsSaveDelaySecondsDisplay {
            get {
                return ResourceManager.GetString("MetricsSaveDelaySecondsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Customer → Cloud Names field is visible..
        /// </summary>
        public static string MetricsShowCustCloudNamesDesc {
            get {
                return ResourceManager.GetString("MetricsShowCustCloudNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Names.
        /// </summary>
        public static string MetricsShowCustCloudNamesDisplay {
            get {
                return ResourceManager.GetString("MetricsShowCustCloudNamesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Customer → Corporation field is visible..
        /// </summary>
        public static string MetricsShowCustCorporationDesc {
            get {
                return ResourceManager.GetString("MetricsShowCustCorporationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string MetricsShowCustCorporationDisplay {
            get {
                return ResourceManager.GetString("MetricsShowCustCorporationDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Customer → Info field is visible..
        /// </summary>
        public static string MetricsShowCustInfoDesc {
            get {
                return ResourceManager.GetString("MetricsShowCustInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MetricsShowCustInfoDisplay {
            get {
                return ResourceManager.GetString("MetricsShowCustInfoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Customer → Logo field is visible..
        /// </summary>
        public static string MetricsShowCustLogoDesc {
            get {
                return ResourceManager.GetString("MetricsShowCustLogoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string MetricsShowCustLogoDisplay {
            get {
                return ResourceManager.GetString("MetricsShowCustLogoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Customer → Signin Logo field is visible..
        /// </summary>
        public static string MetricsShowCustSigninLogoDesc {
            get {
                return ResourceManager.GetString("MetricsShowCustSigninLogoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin Logo.
        /// </summary>
        public static string MetricsShowCustSigninLogoDisplay {
            get {
                return ResourceManager.GetString("MetricsShowCustSigninLogoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Customer → Signin Note field is visible..
        /// </summary>
        public static string MetricsShowCustSigninNoteDesc {
            get {
                return ResourceManager.GetString("MetricsShowCustSigninNoteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin Note.
        /// </summary>
        public static string MetricsShowCustSigninNoteDisplay {
            get {
                return ResourceManager.GetString("MetricsShowCustSigninNoteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Customer Names field is visible..
        /// </summary>
        public static string MetricsShowUserCustNamesDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserCustNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Customers.
        /// </summary>
        public static string MetricsShowUserCustNamesDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserCustNamesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Dashboard Names field is visible..
        /// </summary>
        public static string MetricsShowUserDashboardNamesDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserDashboardNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Names.
        /// </summary>
        public static string MetricsShowUserDashboardNamesDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserDashboardNamesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Data Location field is visible..
        /// </summary>
        public static string MetricsShowUserDataLocationDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserDataLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Location.
        /// </summary>
        public static string MetricsShowUserDataLocationDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserDataLocationDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Email field is visible..
        /// </summary>
        public static string MetricsShowUserEmailDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserEmailDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string MetricsShowUserEmailDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserEmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Job Names field is visible..
        /// </summary>
        public static string MetricsShowUserJobNamesDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserJobNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Jobs.
        /// </summary>
        public static string MetricsShowUserJobNamesDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserJobNamesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Uid field is visible..
        /// </summary>
        public static string MetricsShowUserUidDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserUidDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uid.
        /// </summary>
        public static string MetricsShowUserUidDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserUidDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the User → Vartree Names field is visible..
        /// </summary>
        public static string MetricsShowUserVartreeNamesDesc {
            get {
                return ResourceManager.GetString("MetricsShowUserVartreeNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vartree Names.
        /// </summary>
        public static string MetricsShowUserVartreeNamesDisplay {
            get {
                return ResourceManager.GetString("MetricsShowUserVartreeNamesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Upload.
        /// </summary>
        public static string MetricsUploadCategory {
            get {
                return ResourceManager.GetString("MetricsUploadCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma or space separated names of directories to pre-select for upload (case insensitive)..
        /// </summary>
        public static string MetricsUploadDirNamesDesc {
            get {
                return ResourceManager.GetString("MetricsUploadDirNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folders.
        /// </summary>
        public static string MetricsUploadDirNamesDisplay {
            get {
                return ResourceManager.GetString("MetricsUploadDirNamesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma or space separated dot-prefixed file extensions to pre-select for upload (case insensitive)..
        /// </summary>
        public static string MetricsUploadExtensionsDesc {
            get {
                return ResourceManager.GetString("MetricsUploadExtensionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Extensions.
        /// </summary>
        public static string MetricsUploadExtensionsDisplay {
            get {
                return ResourceManager.GetString("MetricsUploadExtensionsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Visibility.
        /// </summary>
        public static string MetricsUserVisibilityCategory {
            get {
                return ResourceManager.GetString("MetricsUserVisibilityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string NavNodeCustomers {
            get {
                return ResourceManager.GetString("NavNodeCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string NavNodeJobs {
            get {
                return ResourceManager.GetString("NavNodeJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realms.
        /// </summary>
        public static string NavNodeRealms {
            get {
                return ResourceManager.GetString("NavNodeRealms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string NavNodeUsers {
            get {
                return ResourceManager.GetString("NavNodeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad connection string.
        /// </summary>
        public static string NewCustBadConnect {
            get {
                return ResourceManager.GetString("NewCustBadConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer name.
        /// </summary>
        public static string NewCustBadName {
            get {
                return ResourceManager.GetString("NewCustBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter connection string.
        /// </summary>
        public static string NewCustNoConnect {
            get {
                return ResourceManager.GetString("NewCustNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad connections string.
        /// </summary>
        public static string NewCustomerBadConnect {
            get {
                return ResourceManager.GetString("NewCustomerBadConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new customer {0}.
        /// </summary>
        public static string NewCustomerBusy {
            get {
                return ResourceManager.GetString("NewCustomerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string NewCustomerDialogTitle {
            get {
                return ResourceManager.GetString("NewCustomerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new licensing customer also creates an Azure Storage Account which is associated with the customer..
        /// </summary>
        public static string NewCustomerInstructions {
            get {
                return ResourceManager.GetString("NewCustomerInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad job name.
        /// </summary>
        public static string NewJobBadName {
            get {
                return ResourceManager.GetString("NewJobBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate job name.
        /// </summary>
        public static string NewJobDuplicateName {
            get {
                return ResourceManager.GetString("NewJobDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new job must be initially connected to a parent customer. The customer can&apos;t be changed after the job is created..
        /// </summary>
        public static string NewJobInstructions {
            get {
                return ResourceManager.GetString("NewJobInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account {0} has reached the limit of {1} jobs. Contact Red Centre Software to enable a larger job quota..
        /// </summary>
        public static string NewJobLimit {
            get {
                return ResourceManager.GetString("NewJobLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select customer.
        /// </summary>
        public static string NewJobNoCustomer {
            get {
                return ResourceManager.GetString("NewJobNoCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter job name.
        /// </summary>
        public static string NewJobNoName {
            get {
                return ResourceManager.GetString("NewJobNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Realm name.
        /// </summary>
        public static string NewRealmBadName {
            get {
                return ResourceManager.GetString("NewRealmBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Realm name.
        /// </summary>
        public static string NewRealmDuplicateName {
            get {
                return ResourceManager.GetString("NewRealmDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Realm name.
        /// </summary>
        public static string NewRealmNoname {
            get {
                return ResourceManager.GetString("NewRealmNoname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of the assembly {0} is unavailable.
        /// </summary>
        public static string NoAsmLocation {
            get {
                return ResourceManager.GetString("NoAsmLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .NET class types acting as licensing providers were found in any assemblies in {0}.
        /// </summary>
        public static string NoProviderTypes {
            get {
                return ResourceManager.GetString("NoProviderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string NoSelectId {
            get {
                return ResourceManager.GetString("NoSelectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- SELECT ---.
        /// </summary>
        public static string NoSelectText {
            get {
                return ResourceManager.GetString("NoSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container &apos;{0}&apos; does not contain both a job.ini file and a CaseData sub-directory. It may not contain a valid Ruby Job. Do you want to continue and convert the container to a job?.
        /// </summary>
        public static string NotJobContainerPrompt {
            get {
                return ResourceManager.GetString("NotJobContainerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not contain both a job.ini file and a CaseData sub-directory. It may not contain a valid Ruby Job. Do you want to continue and select the directory?.
        /// </summary>
        public static string NotJobDirectoryPrompt {
            get {
                return ResourceManager.GetString("NotJobDirectoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor count for type {0} is {1}, expected 1 - Skipped..
        /// </summary>
        public static string SkipConstructor {
            get {
                return ResourceManager.GetString("SkipConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Storage Account and licensing customer record both exist..
        /// </summary>
        public static string StorageAndCustomerOK {
            get {
                return ResourceManager.GetString("StorageAndCustomerOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Storage Account associated with the customer is inaccessible. Check that the connection string is specified and valid..
        /// </summary>
        public static string StorageInaccessible {
            get {
                return ResourceManager.GetString("StorageInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an instance of type &apos;{0}&apos; (parameter count {1})..
        /// </summary>
        public static string TypeCreateFail {
            get {
                return ResourceManager.GetString("TypeCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating customer.
        /// </summary>
        public static string UpdateCustomerBusy {
            get {
                return ResourceManager.GetString("UpdateCustomerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating job.
        /// </summary>
        public static string UpdateJobBusy {
            get {
                return ResourceManager.GetString("UpdateJobBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating realm.
        /// </summary>
        public static string UpdateRealmBusy {
            get {
                return ResourceManager.GetString("UpdateRealmBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating user.
        /// </summary>
        public static string UpdateUserBusy {
            get {
                return ResourceManager.GetString("UpdateUserBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import rejected. All of the user names already exist in the licensing database..
        /// </summary>
        public static string UserImportAllDuplicates {
            get {
                return ResourceManager.GetString("UserImportAllDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import worksheet does not define any users.
        /// </summary>
        public static string UserImportNoUsers {
            get {
                return ResourceManager.GetString("UserImportNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name is not a valid email address..
        /// </summary>
        public static string UserNotEmail {
            get {
                return ResourceManager.GetString("UserNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating customer {0}.
        /// </summary>
        public static string ValidateCustomerBusy {
            get {
                return ResourceManager.GetString("ValidateCustomerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed
        ///
        ///Customer Id {0} Name {1} returned the following errors attempting to access the corresponding Azure Storage Account:
        ///
        ///{2}.
        /// </summary>
        public static string ValidateCustomerFail {
            get {
                return ResourceManager.GetString("ValidateCustomerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Passed
        ///
        ///Customer Id {0} Name {1} has a corresponding Azure Storage Account and it is accessible..
        /// </summary>
        public static string ValidateCustomerPass {
            get {
                return ResourceManager.GetString("ValidateCustomerPass", resourceCulture);
            }
        }
    }
}
